[package]
name = "dioxus-router-core"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-lock = "2.7.0"
futures-channel = "0.3.28"
futures-util = "0.3.28"
